# Generated by Django 5.2.5 on 2025-09-13 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0003_alter_customer_options_customer_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property_address",
                    models.TextField(
                        help_text="The full address of the leased property."
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "rent_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The monthly rent amount.",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("PENDING", "Pending"),
                            ("TERMINATED", "Terminated"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="The customer who holds this lease.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leases",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
    ]
