# Generated by Django 5.2.4 on 2025-08-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tenants",
            field=models.ManyToManyField(
                blank=True,
                help_text="The tenants this user has access to.",
                to="tenants.admintenant",
            ),
        ),
    ]
