# Generated by Django 5.2.4 on 2025-08-08 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_customer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
