# Generated by Django 5.2.5 on 2025-08-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_delete_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="admintenant",
            name="branding_logo",
            field=models.ImageField(blank=True, null=True, upload_to="tenant_logos/"),
        ),
        migrations.AddField(
            model_name="admintenant",
            name="branding_site_header",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="admintenant",
            name="branding_site_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="admintenant",
            name="branding_welcome_sign",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
